apiVersion: v1
kind: Pod
metadata:
  name: oran-pod
spec:
  containers:
  - name: oran-container
    image: localhost:5000/oai-oran-7.2:v1.2
    command: ["sleep", "infinity"]
    securityContext:
      privileged: true
      capabilities:
        add: ["NET_ADMIN", "SYS_RAWIO", "SYS_NICE", "IPC_LOCK"]
    resources:
      limits:
        cpu: "11" # Total number of isolated CPUs
        memory: "82Gi"
        intel.com/intel_oran_sriov: "2"
        hugepages-1Gi: "10Gi"
      requests:
        cpu: "7"
        memory: "82Gi"
        intel.com/intel_oran_sriov: "2"
        hugepages-1Gi: "10Gi"
    volumeMounts:
    - name: local-lib64
      mountPath: /usr/local/lib64
      readOnly: true
    - name: local-include
      mountPath: /usr/local/include
      readOnly: true
    - name: local-lib
      mountPath: /usr/local/lib
      readOnly: true
    - name: usr-lib64
      mountPath: /usr/lib64
    - name: cpufreq
      mountPath: /sys/devices/system/cpu
    - name: hugepages
      mountPath: /dev/hugepages
  volumes:
  - name: local-lib64
    hostPath:
      path: /usr/local/lib64
  - name: local-include
    hostPath:
      path: /usr/local/include
  - name: local-lib
    hostPath:
      path: /usr/local/lib
  - name: usr-lib64
    hostPath:
      path: /usr/lib64/
  - name: cpufreq
    hostPath:
      path: /sys/devices/system/cpu
      type: Directory
  - name: hugepages
    hostPath:
      path: /dev/hugepages
      type: Directory
