apiVersion: v1
kind: ConfigMap
metadata:
  name: sriovdp-config
data:
  config.json: |
    {
      "resourceList": [
        {
          "resourcePrefix": "intel.com",
          "resourceName": "intel_oran_sriov",
          "selectors": {
            "vendors": ["8086"],
            "drivers": ["vfio-pci"],
            "pciAddresses": ["0000:8a:02.0", "0000:8a:02.1"]
          }
        }
      ]
    }
